"""
Overlay Generator Module

Manages the guidance overlay stream by monitoring for static PNG files
generated by the guidance system.
"""

import cv2
import numpy as np
from pathlib import Path
from typing import Optional
import os
import time


class OverlayGenerator:
    """
    Manages the guidance overlay stream.

    The guidance module signals that a new overlay is available by updating
    a flag file. This class monitors that flag and loads the corresponding
    overlay image when available.
    """

    def __init__(self, overlay_path: str = "data/guidance_overlay.png",
                 flag_path: str = "data/overlay_ready.flag"):
        """
        Initialize the overlay generator.

        Args:
            overlay_path: Path where guidance saves the overlay PNG
            flag_path: Path to flag file indicating new overlay is ready
        """
        self.overlay_path = Path(overlay_path)
        self.flag_path = Path(flag_path)
        self.current_overlay: Optional[np.ndarray] = None
        self.last_modified: float = 0.0

    def check_for_update(self) -> bool:
        """
        Check if a new overlay is available.

        Returns:
            True if new overlay detected, False otherwise
        """
        # Check if flag file exists and has been modified
        if self.flag_path.exists():
            flag_mtime = os.path.getmtime(self.flag_path)
            if flag_mtime > self.last_modified:
                # New overlay available
                self.last_modified = flag_mtime
                return True
        return False

    def load_overlay(self) -> bool:
        """
        Load the latest overlay from disk.

        Returns:
            True if loaded successfully, False otherwise
        """
        if not self.overlay_path.exists():
            return False

        try:
            # Load overlay image
            overlay = cv2.imread(str(self.overlay_path))
            if overlay is not None:
                self.current_overlay = overlay
                print(f"[OverlayGenerator] Loaded new overlay from {self.overlay_path}")
                return True
        except Exception as e:
            print(f"[OverlayGenerator] Error loading overlay: {e}")

        return False

    def get_overlay(self) -> Optional[np.ndarray]:
        """
        Get the current overlay frame.

        Automatically checks for updates and loads new overlay if available.

        Returns:
            Current overlay as numpy array (BGR), or None if unavailable
        """
        # Check for new overlay
        if self.check_for_update():
            self.load_overlay()

        # Return current overlay
        return self.current_overlay.copy() if self.current_overlay is not None else None

    def clear_overlay(self):
        """Clear the current overlay."""
        self.current_overlay = None
        print("[OverlayGenerator] Overlay cleared")

    def has_overlay(self) -> bool:
        """Check if an overlay is currently available."""
        return self.current_overlay is not None

    def signal_overlay_ready(self):
        """
        Signal that a new overlay is ready (called by guidance system).

        This creates/updates the flag file to trigger overlay reload.
        """
        self.flag_path.parent.mkdir(parents=True, exist_ok=True)
        self.flag_path.touch()
        print(f"[OverlayGenerator] Signaled overlay ready")

    def save_overlay(self, overlay: np.ndarray):
        """
        Save an overlay and signal it's ready (called by guidance system).

        Args:
            overlay: Overlay image to save
        """
        self.overlay_path.parent.mkdir(parents=True, exist_ok=True)
        cv2.imwrite(str(self.overlay_path), overlay)
        self.signal_overlay_ready()
